-- Share Steps MVP SQL runner note.
-- Supabase SQL Editor has a paste limit in this environment, so run these
-- files one by one in order:
--
-- 1. supabase/01_tables.sql
-- 2. supabase/02_functions.sql
-- 3. supabase/03_rls_policies.sql
-- 4. supabase/04_indexes.sql
--
-- Each file is under 100 lines.
